env:
  browser: true
  es6: true
  jasmine: true
extends: 'airbnb'
parser: babel-eslint
parserOptions:
  ecmaFeatures:
    experimentalObjectRestSpread: true
    jsx: true
    impliedStrict: true
  sourceType: module
plugins:
  - react
  - flowtype
  - jsx-a11y
rules:
  # Possible errors
  no-console: warn

  # Best Practices
  array-callback-return: error
  block-scoped-var: error
  curly: error
  default-case: error
  dot-location:
    - error
    - property
  dot-notation: error
  eqeqeq: error
  no-alert: error
  no-case-declarations: error
  no-else-return: error
  no-extend-native: error
  no-extra-bind: error
  no-fallthrough: error
  no-floating-decimal: error
  no-implicit-coercion: error
  no-implicit-globals: error
  no-invalid-this: error
  no-iterator: error
  no-labels: error
  no-lone-blocks: error
  no-multi-spaces: error
  no-native-reassign: error
  no-new: error
  no-new-func: error
  no-new-wrappers: error
  no-octal: error
  no-octal-escape: error
  no-param-reassign: error
  no-proto: error
  no-return-assign: error
  no-self-assign: error
  no-self-compare: error
  no-sequences: error
  no-throw-literal: error
  no-unmodified-loop-condition: error
  no-unused-expressions: error
  no-useless-call: error
  no-useless-concat: error
  no-void: error
  no-warning-comments: warn
  no-with: error
  wrap-iife: error
  yoda: error

  # Strict Mode
  strict: error

  # Variables
  no-catch-shadow: error
  no-restricted-globals: error
  no-shadow: error
  no-shadow-restricted-names: error
  no-undef-init: error
  no-undefined: error
  no-unused-vars: warn
  no-use-before-define: error

  # Stylistic Issues
  array-bracket-spacing: error
  block-spacing: error
  brace-style:
    - error
    - 1tbs
    - allowSingleLine: true
  camelcase: error
  comma-spacing: error
  comma-style: error
  computed-property-spacing: error
  eol-last: error
  func-style: error
  indent:
    - error
    - 2
  jsx-quotes: error
  key-spacing: error
  keyword-spacing: error
  linebreak-style: error
  max-len:
    - warn
    - 120
    - 2
  new-cap:
    - error
    - capIsNewExceptions:
      - Immutable
  new-parens: error
  newline-after-var: error
  newline-before-return: error
  newline-per-chained-call: error
  no-array-constructor: error
  no-bitwise: error
  no-lonely-if: error
  no-multiple-empty-lines: error
  no-negated-condition: error
  no-nested-ternary: error
  no-new-object: error
  no-spaced-func: error
  no-trailing-spaces: error
  no-underscore-dangle: error
  no-unneeded-ternary: error
  no-whitespace-before-property: error
  object-curly-spacing:
    - error
    - always
  one-var-declaration-per-line:
    - error
    - initializations
  operator-assignment: error
  operator-linebreak: error
  padded-blocks:
    - error
    - never
  quote-props:
    - error
    - as-needed
  quotes:
    - error
    - single
    - avoid-escape
  semi: error
  semi-spacing: error
  space-before-blocks: error
  space-before-function-paren:
    - error
    - never
  space-in-parens: error
  space-infix-ops: error
  space-unary-ops: error
  spaced-comment: error
  wrap-regex: error

  # ECMAScript 6
  arrow-body-style: error
  arrow-parens:
    - error
    - as-needed
  arrow-spacing: error
  generator-star-spacing: error
  no-confusing-arrow: error
  no-useless-constructor: error
  no-var: error
  object-shorthand: error
  prefer-arrow-callback: error
  prefer-const: error
  prefer-reflect: error
  prefer-rest-params: error
  prefer-spread: error
  prefer-template: error
  require-yield: error
  template-curly-spacing: error
  yield-star-spacing: error

  # React
  react/no-did-mount-set-state: error
  react/no-did-update-set-state: error
  react/no-deprecated: error
  react/no-unknown-property: error
  react/prefer-stateless-function: error
  react/prop-types: error
  react/react-in-jsx-scope: error
  react/self-closing-comp: error
  react/sort-comp: error
  react/sort-prop-types:
    - error
    - callbacksLast: true
      requiredFirst: true
  react/wrap-multilines: error

  # JSX
  react/jsx-boolean-value:
    - error
    - never
  react/jsx-closing-bracket-location: error
  react/jsx-curly-spacing:
    - error
    - never
    - allowMultiline: false
  react/jsx-equals-spacing: error
  react/jsx-handler-names: error
  react/jsx-indent-props:
    - error
    - 2
  react/jsx-indent:
    - error
    - 2
  react/jsx-key: error
  react/jsx-no-bind: error
  react/jsx-no-duplicate-props: error
  react/jsx-no-undef: error
  react/jsx-pascal-case: error
  react/jsx-sort-props:
    - error
    - callbacksLast: true
  react/jsx-space-before-closing:
    - error
    - never
  react/jsx-uses-react: error
  react/jsx-uses-vars: error

  #Flow:
  #require-parameter-type: warn
  #require-return-type: warn
  flowtype/space-after-type-colon: error
  flowtype/space-before-type-colon: error
